# Generated by Django 4.1.3 on 2022-11-30 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_alter_classroom_table_alter_student_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='classroom',
            table='classrooms',
        ),
    ]
