# Generated by Django 4.1.3 on 2022-11-30 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_alter_classroom_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProxy',
            fields=[
            ],
            options={
                'ordering': ['-id'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('administracion.student',),
        ),
    ]
