# Generated by Django 4.1.3 on 2022-11-30 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_examen_final_proyecto_proyectoproxy'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='examen_final',
            table='final_examens',
        ),
        migrations.AlterModelTable(
            name='proyecto',
            table='proyects',
        ),
    ]
